#!/bin/bash
LOG_DIR="$AIRFLOW_HOME"/logs
# >>>
# >>> Airflow Worker <<<
# >>>
# mkdir -p "$LOG_DIR"/worker
# echo "Starting Airflow Worker"
# airflow celery worker -D --pid "$LOG_DIR"/worker/airflow-worker.pid
# >>>
# >>> Airflow Scheduler <<<
# >>>
mkdir -p "$LOG_DIR"/scheduler
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "Starting Airflow Scheduler"
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<"
SCHEDULER_PID_FILE="$LOG_DIR"/scheduler/airflow-scheduler.pid
if [ -f "$SCHEDULER_PID_FILE" ]; then
  echo "Killing previous Airflow scheduler"
  cat "$SCHEDULER_PID_FILE" | xargs kill -15
  rm -f "$SCHEDULER_PID_FILE"
fi
airflow scheduler -D \
    -l $LOG_DIR/scheduler/airflow-scheduler.log \
    --pid $LOG_DIR/scheduler/airflow-scheduler.pid \
    --stderr $LOG_DIR/scheduler/airflow-scheduler.stderr \
    --stdout $LOG_DIR/scheduler/airflow-scheduler.stdout
# >>>
# >>> Airflow Webserver <<<
# >>>
mkdir -p "$LOG_DIR"/webserver
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "Starting Airflow Webserver"
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<"
WEBSERVER_PID_FILE="$LOG_DIR"/webserver/airflow-webserver.pid
if [ -f "$WEBSERVER_PID_FILE" ]; then
  echo "Killing previous Airflow webserver"
  cat "$WEBSERVER_PID_FILE" | xargs kill -15
  rm -f "$WEBSERVER_PID_FILE"
fi
PORT=8080
airflow webserver -D \
    --port $PORT \
    -A $LOG_DIR/webserver/airflow-webserver.out \
    -E $LOG_DIR/webserver/airflow-webserver.err \
    -l $LOG_DIR/webserver/airflow-webserver.log \
    --pid $LOG_DIR/webserver/airflow-webserver.pid \
    --stderr $LOG_DIR/webserver/airflow-webserver.stderr \
    --stdout $LOG_DIR/webserver/airflow-webserver.stdout
